/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qltv;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author mieum
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnsach = new javax.swing.JButton();
        btnmuontra = new javax.swing.JButton();
        btnnxb = new javax.swing.JButton();
        btndocgia = new javax.swing.JButton();
        btnthoat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnthongke1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btndocgia2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        btnsach.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnsach.setText("Sách");
        btnsach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsachActionPerformed(evt);
            }
        });
        getContentPane().add(btnsach);
        btnsach.setBounds(43, 20, 161, 37);

        btnmuontra.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnmuontra.setText("Mượn trả");
        btnmuontra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmuontraActionPerformed(evt);
            }
        });
        getContentPane().add(btnmuontra);
        btnmuontra.setBounds(43, 69, 161, 37);

        btnnxb.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnnxb.setText("Nhà xuất bản");
        btnnxb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnxbActionPerformed(evt);
            }
        });
        getContentPane().add(btnnxb);
        btnnxb.setBounds(43, 117, 161, 37);

        btndocgia.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btndocgia.setText("Độc giả");
        btndocgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndocgiaActionPerformed(evt);
            }
        });
        getContentPane().add(btndocgia);
        btndocgia.setBounds(40, 170, 161, 37);

        btnthoat.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnthoat.setText("Đăng xuất");
        btnthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthoatActionPerformed(evt);
            }
        });
        getContentPane().add(btnthoat);
        btnthoat.setBounds(410, 280, 131, 37);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Thủ Thư");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 10, 136, 42);

        btnthongke1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnthongke1.setText("Thống kê");
        btnthongke1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthongke1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnthongke1);
        btnthongke1.setBounds(40, 220, 161, 37);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\mieum\\OneDrive\\Pictures\\boss.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 60, 280, 180);

        btndocgia2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btndocgia2.setText("Tìm kiếm");
        btndocgia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndocgia2ActionPerformed(evt);
            }
        });
        getContentPane().add(btndocgia2);
        btndocgia2.setBounds(40, 270, 161, 37);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsachActionPerformed
        // TODO add your handling code here:
        new QLSach().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnsachActionPerformed

    private void btnmuontraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmuontraActionPerformed
        // TODO add your handling code here:
        new MT().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnmuontraActionPerformed

    private void btnnxbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnxbActionPerformed
        // TODO add your handling code here:
        new QLNhaXB().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnnxbActionPerformed

    private void btndocgiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndocgiaActionPerformed
        // TODO add your handling code here:
        new QLDocGia().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btndocgiaActionPerformed

    private void btnthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthoatActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnthoatActionPerformed

    private void btnthongke1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthongke1ActionPerformed
        // TODO add your handling code here:
        new ThongKe().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnthongke1ActionPerformed

    private void btndocgia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndocgia2ActionPerformed
        // TODO add your handling code here:
        new TimKiem().setVisible(true);
    }//GEN-LAST:event_btndocgia2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndocgia;
    private javax.swing.JButton btndocgia2;
    private javax.swing.JButton btnmuontra;
    private javax.swing.JButton btnnxb;
    private javax.swing.JButton btnsach;
    private javax.swing.JButton btnthoat;
    private javax.swing.JButton btnthongke1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
